# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/lds

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/lds

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/lds/CMakeFiles /home/daniel/lds//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/lds/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lds_core

# Build rule for target.
lds_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lds_core
.PHONY : lds_core

# fast build rule for target.
lds_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/build
.PHONY : lds_core/fast

#=============================================================================
# Target rules for targets named lds_app

# Build rule for target.
lds_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lds_app
.PHONY : lds_app

# fast build rule for target.
lds_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_app.dir/build.make CMakeFiles/lds_app.dir/build
.PHONY : lds_app/fast

#=============================================================================
# Target rules for targets named test_reactor

# Build rule for target.
test_reactor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_reactor
.PHONY : test_reactor

# fast build rule for target.
test_reactor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reactor.dir/build.make CMakeFiles/test_reactor.dir/build
.PHONY : test_reactor/fast

app/LDS.o: app/LDS.cpp.o
.PHONY : app/LDS.o

# target to build an object file
app/LDS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_app.dir/build.make CMakeFiles/lds_app.dir/app/LDS.cpp.o
.PHONY : app/LDS.cpp.o

app/LDS.i: app/LDS.cpp.i
.PHONY : app/LDS.i

# target to preprocess a source file
app/LDS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_app.dir/build.make CMakeFiles/lds_app.dir/app/LDS.cpp.i
.PHONY : app/LDS.cpp.i

app/LDS.s: app/LDS.cpp.s
.PHONY : app/LDS.s

# target to generate assembly for a file
app/LDS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_app.dir/build.make CMakeFiles/lds_app.dir/app/LDS.cpp.s
.PHONY : app/LDS.cpp.s

design_patterns/command/src/ICommand.o: design_patterns/command/src/ICommand.cpp.o
.PHONY : design_patterns/command/src/ICommand.o

# target to build an object file
design_patterns/command/src/ICommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/design_patterns/command/src/ICommand.cpp.o
.PHONY : design_patterns/command/src/ICommand.cpp.o

design_patterns/command/src/ICommand.i: design_patterns/command/src/ICommand.cpp.i
.PHONY : design_patterns/command/src/ICommand.i

# target to preprocess a source file
design_patterns/command/src/ICommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/design_patterns/command/src/ICommand.cpp.i
.PHONY : design_patterns/command/src/ICommand.cpp.i

design_patterns/command/src/ICommand.s: design_patterns/command/src/ICommand.cpp.s
.PHONY : design_patterns/command/src/ICommand.s

# target to generate assembly for a file
design_patterns/command/src/ICommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/design_patterns/command/src/ICommand.cpp.s
.PHONY : design_patterns/command/src/ICommand.cpp.s

design_patterns/reactor/src/reactor.o: design_patterns/reactor/src/reactor.cpp.o
.PHONY : design_patterns/reactor/src/reactor.o

# target to build an object file
design_patterns/reactor/src/reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/design_patterns/reactor/src/reactor.cpp.o
.PHONY : design_patterns/reactor/src/reactor.cpp.o

design_patterns/reactor/src/reactor.i: design_patterns/reactor/src/reactor.cpp.i
.PHONY : design_patterns/reactor/src/reactor.i

# target to preprocess a source file
design_patterns/reactor/src/reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/design_patterns/reactor/src/reactor.cpp.i
.PHONY : design_patterns/reactor/src/reactor.cpp.i

design_patterns/reactor/src/reactor.s: design_patterns/reactor/src/reactor.cpp.s
.PHONY : design_patterns/reactor/src/reactor.s

# target to generate assembly for a file
design_patterns/reactor/src/reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/design_patterns/reactor/src/reactor.cpp.s
.PHONY : design_patterns/reactor/src/reactor.cpp.s

services/communication_protocols/nbd/src/DriverData.o: services/communication_protocols/nbd/src/DriverData.cpp.o
.PHONY : services/communication_protocols/nbd/src/DriverData.o

# target to build an object file
services/communication_protocols/nbd/src/DriverData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/nbd/src/DriverData.cpp.o
.PHONY : services/communication_protocols/nbd/src/DriverData.cpp.o

services/communication_protocols/nbd/src/DriverData.i: services/communication_protocols/nbd/src/DriverData.cpp.i
.PHONY : services/communication_protocols/nbd/src/DriverData.i

# target to preprocess a source file
services/communication_protocols/nbd/src/DriverData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/nbd/src/DriverData.cpp.i
.PHONY : services/communication_protocols/nbd/src/DriverData.cpp.i

services/communication_protocols/nbd/src/DriverData.s: services/communication_protocols/nbd/src/DriverData.cpp.s
.PHONY : services/communication_protocols/nbd/src/DriverData.s

# target to generate assembly for a file
services/communication_protocols/nbd/src/DriverData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/nbd/src/DriverData.cpp.s
.PHONY : services/communication_protocols/nbd/src/DriverData.cpp.s

services/communication_protocols/nbd/src/NBDDriverComm.o: services/communication_protocols/nbd/src/NBDDriverComm.cpp.o
.PHONY : services/communication_protocols/nbd/src/NBDDriverComm.o

# target to build an object file
services/communication_protocols/nbd/src/NBDDriverComm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/nbd/src/NBDDriverComm.cpp.o
.PHONY : services/communication_protocols/nbd/src/NBDDriverComm.cpp.o

services/communication_protocols/nbd/src/NBDDriverComm.i: services/communication_protocols/nbd/src/NBDDriverComm.cpp.i
.PHONY : services/communication_protocols/nbd/src/NBDDriverComm.i

# target to preprocess a source file
services/communication_protocols/nbd/src/NBDDriverComm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/nbd/src/NBDDriverComm.cpp.i
.PHONY : services/communication_protocols/nbd/src/NBDDriverComm.cpp.i

services/communication_protocols/nbd/src/NBDDriverComm.s: services/communication_protocols/nbd/src/NBDDriverComm.cpp.s
.PHONY : services/communication_protocols/nbd/src/NBDDriverComm.s

# target to generate assembly for a file
services/communication_protocols/nbd/src/NBDDriverComm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/nbd/src/NBDDriverComm.cpp.s
.PHONY : services/communication_protocols/nbd/src/NBDDriverComm.cpp.s

services/communication_protocols/tcp/src/TCPDriverComm.o: services/communication_protocols/tcp/src/TCPDriverComm.cpp.o
.PHONY : services/communication_protocols/tcp/src/TCPDriverComm.o

# target to build an object file
services/communication_protocols/tcp/src/TCPDriverComm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/tcp/src/TCPDriverComm.cpp.o
.PHONY : services/communication_protocols/tcp/src/TCPDriverComm.cpp.o

services/communication_protocols/tcp/src/TCPDriverComm.i: services/communication_protocols/tcp/src/TCPDriverComm.cpp.i
.PHONY : services/communication_protocols/tcp/src/TCPDriverComm.i

# target to preprocess a source file
services/communication_protocols/tcp/src/TCPDriverComm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/tcp/src/TCPDriverComm.cpp.i
.PHONY : services/communication_protocols/tcp/src/TCPDriverComm.cpp.i

services/communication_protocols/tcp/src/TCPDriverComm.s: services/communication_protocols/tcp/src/TCPDriverComm.cpp.s
.PHONY : services/communication_protocols/tcp/src/TCPDriverComm.s

# target to generate assembly for a file
services/communication_protocols/tcp/src/TCPDriverComm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/communication_protocols/tcp/src/TCPDriverComm.cpp.s
.PHONY : services/communication_protocols/tcp/src/TCPDriverComm.cpp.s

services/local_storage/src/IStorage.o: services/local_storage/src/IStorage.cpp.o
.PHONY : services/local_storage/src/IStorage.o

# target to build an object file
services/local_storage/src/IStorage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/IStorage.cpp.o
.PHONY : services/local_storage/src/IStorage.cpp.o

services/local_storage/src/IStorage.i: services/local_storage/src/IStorage.cpp.i
.PHONY : services/local_storage/src/IStorage.i

# target to preprocess a source file
services/local_storage/src/IStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/IStorage.cpp.i
.PHONY : services/local_storage/src/IStorage.cpp.i

services/local_storage/src/IStorage.s: services/local_storage/src/IStorage.cpp.s
.PHONY : services/local_storage/src/IStorage.s

# target to generate assembly for a file
services/local_storage/src/IStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/IStorage.cpp.s
.PHONY : services/local_storage/src/IStorage.cpp.s

services/local_storage/src/LocalStorage.o: services/local_storage/src/LocalStorage.cpp.o
.PHONY : services/local_storage/src/LocalStorage.o

# target to build an object file
services/local_storage/src/LocalStorage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/LocalStorage.cpp.o
.PHONY : services/local_storage/src/LocalStorage.cpp.o

services/local_storage/src/LocalStorage.i: services/local_storage/src/LocalStorage.cpp.i
.PHONY : services/local_storage/src/LocalStorage.i

# target to preprocess a source file
services/local_storage/src/LocalStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/LocalStorage.cpp.i
.PHONY : services/local_storage/src/LocalStorage.cpp.i

services/local_storage/src/LocalStorage.s: services/local_storage/src/LocalStorage.cpp.s
.PHONY : services/local_storage/src/LocalStorage.s

# target to generate assembly for a file
services/local_storage/src/LocalStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/LocalStorage.cpp.s
.PHONY : services/local_storage/src/LocalStorage.cpp.s

services/local_storage/src/RAIDManager.o: services/local_storage/src/RAIDManager.cpp.o
.PHONY : services/local_storage/src/RAIDManager.o

# target to build an object file
services/local_storage/src/RAIDManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/RAIDManager.cpp.o
.PHONY : services/local_storage/src/RAIDManager.cpp.o

services/local_storage/src/RAIDManager.i: services/local_storage/src/RAIDManager.cpp.i
.PHONY : services/local_storage/src/RAIDManager.i

# target to preprocess a source file
services/local_storage/src/RAIDManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/RAIDManager.cpp.i
.PHONY : services/local_storage/src/RAIDManager.cpp.i

services/local_storage/src/RAIDManager.s: services/local_storage/src/RAIDManager.cpp.s
.PHONY : services/local_storage/src/RAIDManager.s

# target to generate assembly for a file
services/local_storage/src/RAIDManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/local_storage/src/RAIDManager.cpp.s
.PHONY : services/local_storage/src/RAIDManager.cpp.s

services/mediator/src/InputMediator.o: services/mediator/src/InputMediator.cpp.o
.PHONY : services/mediator/src/InputMediator.o

# target to build an object file
services/mediator/src/InputMediator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/mediator/src/InputMediator.cpp.o
.PHONY : services/mediator/src/InputMediator.cpp.o

services/mediator/src/InputMediator.i: services/mediator/src/InputMediator.cpp.i
.PHONY : services/mediator/src/InputMediator.i

# target to preprocess a source file
services/mediator/src/InputMediator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/mediator/src/InputMediator.cpp.i
.PHONY : services/mediator/src/InputMediator.cpp.i

services/mediator/src/InputMediator.s: services/mediator/src/InputMediator.cpp.s
.PHONY : services/mediator/src/InputMediator.s

# target to generate assembly for a file
services/mediator/src/InputMediator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/services/mediator/src/InputMediator.cpp.s
.PHONY : services/mediator/src/InputMediator.cpp.s

test/unit/test_reactor.o: test/unit/test_reactor.cpp.o
.PHONY : test/unit/test_reactor.o

# target to build an object file
test/unit/test_reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reactor.dir/build.make CMakeFiles/test_reactor.dir/test/unit/test_reactor.cpp.o
.PHONY : test/unit/test_reactor.cpp.o

test/unit/test_reactor.i: test/unit/test_reactor.cpp.i
.PHONY : test/unit/test_reactor.i

# target to preprocess a source file
test/unit/test_reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reactor.dir/build.make CMakeFiles/test_reactor.dir/test/unit/test_reactor.cpp.i
.PHONY : test/unit/test_reactor.cpp.i

test/unit/test_reactor.s: test/unit/test_reactor.cpp.s
.PHONY : test/unit/test_reactor.s

# target to generate assembly for a file
test/unit/test_reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reactor.dir/build.make CMakeFiles/test_reactor.dir/test/unit/test_reactor.cpp.s
.PHONY : test/unit/test_reactor.cpp.s

utilities/logger/src/logger.o: utilities/logger/src/logger.cpp.o
.PHONY : utilities/logger/src/logger.o

# target to build an object file
utilities/logger/src/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/utilities/logger/src/logger.cpp.o
.PHONY : utilities/logger/src/logger.cpp.o

utilities/logger/src/logger.i: utilities/logger/src/logger.cpp.i
.PHONY : utilities/logger/src/logger.i

# target to preprocess a source file
utilities/logger/src/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/utilities/logger/src/logger.cpp.i
.PHONY : utilities/logger/src/logger.cpp.i

utilities/logger/src/logger.s: utilities/logger/src/logger.cpp.s
.PHONY : utilities/logger/src/logger.s

# target to generate assembly for a file
utilities/logger/src/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/utilities/logger/src/logger.cpp.s
.PHONY : utilities/logger/src/logger.cpp.s

utilities/threading/thread_pool/src/thread_pool.o: utilities/threading/thread_pool/src/thread_pool.cpp.o
.PHONY : utilities/threading/thread_pool/src/thread_pool.o

# target to build an object file
utilities/threading/thread_pool/src/thread_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/utilities/threading/thread_pool/src/thread_pool.cpp.o
.PHONY : utilities/threading/thread_pool/src/thread_pool.cpp.o

utilities/threading/thread_pool/src/thread_pool.i: utilities/threading/thread_pool/src/thread_pool.cpp.i
.PHONY : utilities/threading/thread_pool/src/thread_pool.i

# target to preprocess a source file
utilities/threading/thread_pool/src/thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/utilities/threading/thread_pool/src/thread_pool.cpp.i
.PHONY : utilities/threading/thread_pool/src/thread_pool.cpp.i

utilities/threading/thread_pool/src/thread_pool.s: utilities/threading/thread_pool/src/thread_pool.cpp.s
.PHONY : utilities/threading/thread_pool/src/thread_pool.s

# target to generate assembly for a file
utilities/threading/thread_pool/src/thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lds_core.dir/build.make CMakeFiles/lds_core.dir/utilities/threading/thread_pool/src/thread_pool.cpp.s
.PHONY : utilities/threading/thread_pool/src/thread_pool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lds_app"
	@echo "... lds_core"
	@echo "... test_reactor"
	@echo "... app/LDS.o"
	@echo "... app/LDS.i"
	@echo "... app/LDS.s"
	@echo "... design_patterns/command/src/ICommand.o"
	@echo "... design_patterns/command/src/ICommand.i"
	@echo "... design_patterns/command/src/ICommand.s"
	@echo "... design_patterns/reactor/src/reactor.o"
	@echo "... design_patterns/reactor/src/reactor.i"
	@echo "... design_patterns/reactor/src/reactor.s"
	@echo "... services/communication_protocols/nbd/src/DriverData.o"
	@echo "... services/communication_protocols/nbd/src/DriverData.i"
	@echo "... services/communication_protocols/nbd/src/DriverData.s"
	@echo "... services/communication_protocols/nbd/src/NBDDriverComm.o"
	@echo "... services/communication_protocols/nbd/src/NBDDriverComm.i"
	@echo "... services/communication_protocols/nbd/src/NBDDriverComm.s"
	@echo "... services/communication_protocols/tcp/src/TCPDriverComm.o"
	@echo "... services/communication_protocols/tcp/src/TCPDriverComm.i"
	@echo "... services/communication_protocols/tcp/src/TCPDriverComm.s"
	@echo "... services/local_storage/src/IStorage.o"
	@echo "... services/local_storage/src/IStorage.i"
	@echo "... services/local_storage/src/IStorage.s"
	@echo "... services/local_storage/src/LocalStorage.o"
	@echo "... services/local_storage/src/LocalStorage.i"
	@echo "... services/local_storage/src/LocalStorage.s"
	@echo "... services/local_storage/src/RAIDManager.o"
	@echo "... services/local_storage/src/RAIDManager.i"
	@echo "... services/local_storage/src/RAIDManager.s"
	@echo "... services/mediator/src/InputMediator.o"
	@echo "... services/mediator/src/InputMediator.i"
	@echo "... services/mediator/src/InputMediator.s"
	@echo "... test/unit/test_reactor.o"
	@echo "... test/unit/test_reactor.i"
	@echo "... test/unit/test_reactor.s"
	@echo "... utilities/logger/src/logger.o"
	@echo "... utilities/logger/src/logger.i"
	@echo "... utilities/logger/src/logger.s"
	@echo "... utilities/threading/thread_pool/src/thread_pool.o"
	@echo "... utilities/threading/thread_pool/src/thread_pool.i"
	@echo "... utilities/threading/thread_pool/src/thread_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

